

services:
  service1:
    build:
      context: micro-services/service1
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  service2:
    build:
      context: micro-services/serviceTwo
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

