POST http://localhost:8080/register
Content-Type: "application/json"

{
    "name": "service1",
    "base_path": "/service1",
    "instances": [
        { "url": "http://localhost:3001", "methods": "GET" },
        { "url": "http://localhost:3002", "methods": "GET" }
    ]
}

###
GET  http://localhost:8080/routes
